<?php

return [
    'body_types' => [
        'SUV',
        'Sedan',
        'Hatchback',
        'Pick-Up',
        'Coupe',
        'Convertible',
        'Van',
        'Wagon',
        'Crossover',
        'Microbus',
    ],
    'fuel_types' => [
        'Gasolina',
        'Diesel',
        'Hibrido',
        'Electrico',
        'PHEV',
        'GLP',
    ],
    'transmissions' => [
        'Automatica',
        'Manual',
        'CVT',
        'DCT',
        'Semi-automatica',
    ],
    'drivetrains' => [
        '4x2',
        '4x4',
        'AWD',
        'FWD',
        'RWD',
    ],
    'conditions' => [
        'used' => 'Usado',
        'new' => 'Nuevo',
    ],
    'currencies' => [
        'USD',
        'CRC',
    ],
    'provinces' => [
        'San Jose',
        'Alajuela',
        'Cartago',
        'Heredia',
        'Guanacaste',
        'Puntarenas',
        'Limon',
    ],
    'cities' => [
        'San Jose',
        'Escazu',
        'Santa Ana',
        'Alajuela',
        'Heredia',
        'Cartago',
        'Desamparados',
        'Curridabat',
        'Tres Rios',
        'Moravia',
        'Goicoechea',
        'Coronado',
        'Aserri',
        'San Ramon',
        'Grecia',
        'Atenas',
        'Liberia',
        'Nicoya',
        'Santa Cruz',
        'Puntarenas',
        'Perez Zeledon',
        'Limon',
        'Guapiles',
        'Turrialba',
        'Ciudad Quesada',
        'Jaco',
        'Quepos',
        'Parrita',
        'Golfito',
        'Siquirres',
    ],
    'photo_slots' => [
        'frontal' => 'Foto frontal',
        'trasera' => 'Foto trasera',
        'lateral_izquierdo' => 'Lateral izquierdo',
        'lateral_derecho' => 'Lateral derecho',
        'interior_conductor' => 'Interior conductor',
        'interior_copiloto' => 'Interior copiloto',
        'interior_pasajeros' => 'Interior pasajeros',
        'motor' => 'Motor',
    ],
];
