<?php

return [
    'body_types' => [
        'SUV',
        'Sedan',
        'Hatchback',
        'Pick-Up',
        'Coupe',
        'Convertible',
        'Van',
        'Wagon',
        'Crossover',
        'Microbus',
    ],
    'fuel_types' => [
        'Gasolina',
        'Diesel',
        'Híbrido',
        'Electrico',
        'PHEV',
        'GLP',
    ],
    'transmissions' => [
        'Automatica',
        'Manual',
        'CVT',
        'DCT',
        'Semi-automatica',
    ],
    'drivetrains' => [
        '4x2',
        '4x4',
        'AWD',
        'FWD',
        'RWD',
    ],
    'conditions' => [
        'used' => 'Usado',
        'new' => 'Nuevo',
    ],
    'currencies' => [
        'USD',
        'CRC',
    ],
    'provinces' => [
        'San José',
        'Alajuela',
        'Cartago',
        'Heredia',
        'Guanacaste',
        'Puntarenas',
        'Limón',
    ],
    'cities' => [
        'San José',
        'Escazú',
        'Santa Ana',
        'Alajuela',
        'Heredia',
        'Cartago',
        'Desamparados',
        'Curridabat',
        'Tres Ríos',
        'Moravia',
        'Goicoechea',
        'Coronado',
        'Aserrí',
        'San Ramón',
        'Grecia',
        'Atenas',
        'Liberia',
        'Nicoya',
        'Santa Cruz',
        'Puntarenas',
        'Pérez Zeledón',
        'Limón',
        'Guápiles',
        'Turrialba',
        'Ciudad Quesada',
        'Jacó',
        'Quepos',
        'Parrita',
        'Golfito',
        'Siquirres',
    ],
    'photo_slots' => [
        'frontal' => 'Foto frontal',
        'trasera' => 'Foto trasera',
        'lateral_izquierdo' => 'Lateral izquierdo',
        'lateral_derecho' => 'Lateral derecho',
        'interior_conductor' => 'Interior conductor',
        'interior_copiloto' => 'Interior',
        'interior_pasajeros' => 'Interior pasajeros',
        'motor' => 'Motor',
    ],
];

